### ISSUE TITLE
Mutable properties

### ISSUE THREAD

**Issue by yonaskolb** [carambalabs/xcodeproj#21]
Since everything is a Struct, should we make all the properties mutable? 
- mutability of a struct can be controlled by using let by whatever contains it, doesn't need to be enforced my it's members
- makes it easier to change values of properties to edit projects (if allowed by above)
- removes the need for functions that return a copy (like `adding(object:)`, or `removing(object:)` functions in PBXProj)
- no danger of things changing from under you like with Classes, where immutable properties pattern would be useful

Thoughts @pepibumur?

**Comment by pepibumur** [comment]
Makes sense. I ended up extending the API unnecessarily because of that. I don't thing there's any downside on making those attributes mutable.
