### ISSUE TITLE
Swift PM error

### ISSUE THREAD

**Issue by yonaskolb** [carambalabs/xcodeproj#22]
The current version of xcodeproj doesn't seem to work as a dependency in other Swift PM projects. The current package is only compatible with Xcode 9, but using the swift CI tools from Xcode 9 and referencing xcodeproj as a dependency leads to the error
```
The product dependency 'xcodepro' was not found
```
I haven't been able to work out the problem. The branch https://github.com/carambalabs/xcodeproj/tree/feature/single_target tries to solve it by exposing only a single target, but that didn't seem to help.

**Comment by yonaskolb** [comment]
Here's an example Package manifest
```
// swift-tools-version:4.0

import PackageDescription

let package = Package(
    name: "xcodepro_tester",
    dependencies: [
        .package(url: "https://github.com/carambalabs/xcodeproj.git", .exact("0.0.6")),
    ],
    targets: [
        .target(name: "xcodepro_tester", dependencies: ["xcodeproj"]),
    ],
    swiftLanguageVersions: [3]
)
```

Note that pulling in xcodeproj before the package changed to Swift 4 worked correctly

**Comment by yonaskolb** [comment]
This still happens with Xcode 9 beta 4. No idea what the problem is. Any thoughts @pepibumur?

**Comment by pepibumur** [comment]
I tried the same the other day @yonaskolb and I got a similar issue, I'll try to figure out where the issue might be.

**Comment by yonaskolb** [comment]
@pepibumur is it ok with you if we roll back the package to Swift 3 anyway, until Swift 4 comes out?

**Comment by Saik0s** [comment]
Hi, I think that I found a solution, adding this line `products: [ .library(name: "xcodeproj", targets: ["xcodeproj"]) ],` to `Package.swift` after `name: "xcodeproj",` will fix this issue. I tested it, and now I can use xcodeproj as a dependency in my package.

**Comment by pepibumur** [comment]
Thanks @Saik0s. @yonaskolb solved it by downgrading the version of the definition that we were using _(we went from 4 to 3)_. We'll try out again once Swift 4 comes out officially.
