### ISSUE TITLE
Crash when opening Framework

### ISSUE THREAD

**Issue by Shakarang** [carambalabs/xcodeproj#38]
## Context

Hey !

First, thanks for your work! 

I'm building a project that uses your library to get all the files within a given Xcode project. It works well for getting the information on iOS/macOS projects but it crashed when I try it on Frameworks (e.g. Alamofire). 

I'm on macOS 10.12.6 and I'm using the version 0.0.9.

## What

When I try to open a Framework, it crashed at this [line](https://github.com/carambalabs/xcodeproj/blob/master/Sources/XCScheme.swift#L113) because the attribute `runnableDebuggingMode` does not exist.

The function is called on this [line](https://github.com/carambalabs/xcodeproj/blob/master/Sources/XCScheme.swift#L289) and the attribute `BuildableProductRunnable` passed in parameter does not exist either.

## Proposal

I saw on this [line](https://github.com/carambalabs/xcodeproj/blob/master/Sources/XCScheme.swift#L108) that if the value is not present, you set it to `"0"` by default. 

Maybe you could do something like this:
```
self.runnableDebuggingMode = element.attributes["runnableDebuggingMode"] ?? "0"
```
Where if the value does not exist, it sets the field to `"0"`. I've tried it on my project and it works with no issue. If you're ok with it, I can do a pull request.

Thanks !

**Comment by yonaskolb** [comment]
Hi @Shakarang 
You're right, that's an issue. If you want to make a pull request, that would be great!
