### ISSUE TITLE
From structs to classes

### ISSUE THREAD

**Issue by pepibumur** [carambalabs/xcodeproj#45]
## Context
All the models in xcodeproj are defined as structs. Although immutability has some advantages like thread safety it makes it forces us to come up with it forces us to extend the interfaces with methods to provide mutated copies of the models with the changes.

You can read more from this issue https://github.com/carambalabs/xcodeproj/issues/43#issuecomment-324315852 that @Daltron reported.

## Proposal
Move the project models to classes and clean up the interfaces removing the methods that are not necessary anymore.

**Comment by Daltron** [comment]
Totally agree going down this path! 👍 👍 👍

**Comment by yonaskolb** [comment]
Another benefit of this is that some PBXObjects could inherit from some abstract base classes and remove a whole bunch of duplicated code

**Comment by yonaskolb** [comment]
Using this now in XcodeGen, it seems it might be better to have `BuildSettings` stay a struct. Now that I look at it though, could `BuildSettings` just be an alias for `[String: Any]`?

**Comment by pepibumur** [comment]
Yes it's much better. `BuildSettings` doesn't add much value to the dictionary.
